### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by duartealexf** [dinevillar/adonis-json-api-serializer#2]
Hey great job with the package. I am currently using it with AdonisJS v4.1 with MongoDB and it's working fine.

I have noticed there is a typo on your README.md, or maybe it's something I had to change to work with the https://github.com/duyluonglc/lucid-mongo package...

In models, where it says...

```js
static get Serializer() {
    return 'JsonApi/Serializer/LucidSerializer';
};
```

I changed to:

```js
const LucidSerializer = use('JsonApi/Serializer/LucidSerializer');

...

static get Serializer() {
    return LucidSerializer;
};
```

**Comment by dinevillar** [comment]
I have not tested this with MongoDB. Reason being is that mongo is not natively supported by Adonis https://adonisjs.com/docs/4.0/database-basics. https://github.com/duyluonglc/lucid-mongo would need to be integrated separately.
